### ISSUE TITLE
Make info page responsive

### ISSUE THREAD

**Issue by ShyrenMore** [ShyrenMore/COVID-19-Hospital-Management#3]
The **info page** which is accessible to both registered and unregistered users is **not responsive for smaller screen sizes like tablet or mobile devices**, to make it responsive you can use media-queries or bootstrap classes.

**Comment by Harshit850** [comment]
@ShyrenMore Consider it done by tomorrow.

**Comment by Harshit850** [comment]
@ShyrenMore I found the info page responsive, i don't there is need of any more responsiveness in there. We just need a navbar at top so that user may return to home page that's it.

**Comment by Harshit850** [comment]
@ShyrenMore Sorry i was busy in some other project, i will fix it by tomorrow.
Can you please tell me the rough layout that you want for your info page, currently it looks great and i don't think there is a need of any modification.

**Comment by ShyrenMore** [comment]
no problem, in mobile view the **SVG illustration is overlapping with text 'Stay home, stay safe'**, kindly do the needful by **positioning the text and illustration** as you think would look good, you can also **change the font-size**, currently it is relatively huge for mobile screen, any additional features would be appreciated, **you are allowed to take your own time implementing this** 😀

**Comment by Harshit850** [comment]
@ShyrenMore Will fix it as soon as possible.

**Comment by Harshit850** [comment]
@ShyrenMore I am really sorry, I tried to fix this issue but i failed. 
It's more complicated than i thought.

**Comment by ShyrenMore** [comment]
It's okay, however if you have any other features in mind do raise an issue for the same
