### ISSUE TITLE
Improve/Update info page

### ISSUE THREAD

**Issue by ShyrenMore** [ShyrenMore/COVID-19-Hospital-Management#4]
In mobile view the **SVG illustration is overlapping with text 'Stay home, stay safe'**, kindly do the needful by **positioning the text and illustration** as you think would look good, you can also **change the font-size**, currently it is relatively huge for mobile screen, any additional features would be appreciated  😀

**Comment by hisa-shimoji** [comment]
Hello, I would like to work on this issue.

**Comment by ShyrenMore** [comment]
Thanks for contributing to this repo!!
